CREATE PROCEDURE [dbo].[BankCardGet]
	@BankCardId INT = NULL
AS
BEGIN
	SET NOCOUNT ON
    SET XACT_ABORT ON

	BEGIN TRAN
		BEGIN TRY
			IF (@BankCardId IS NULL)
			BEGIN
				SELECT * FROM [dbo].[BankCards]
			END
			ELSE
			BEGIN
				SELECT TOP 1 * FROM [dbo].[BankCards] WHERE [Id] = @BankCardId
			END
			COMMIT
		END TRY
		BEGIN CATCH
			IF (@@ERROR <> 0)
			BEGIN 
				ROLLBACK
				;THROW
			END
			RETURN NULL
		END CATCH

END