CREATE TABLE [dbo].[Clubs]
(
	[Id] INT NOT NULL CONSTRAINT PK_Club_Id PRIMARY KEY IDENTITY(1,1)
	,[Name] NVARCHAR(255) NOT NULL
	,[ClubManagerId] INT NULL CONSTRAINT FK_Club_Manager_Id_Clubs_Users FOREIGN KEY REFERENCES [dbo].[Users]
	,[CreatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Created_At_Clubs DEFAULT GETDATE()

)
