CREATE TABLE [dbo].[Locations]
(
	[Id] INT NOT NULL CONSTRAINT PK_Location_Id PRIMARY KEY IDENTITY(1,1)
	--,[Type] NVARCHAR(20) NOT NULL DEFAULT N'UserAddress'
	,[City] NVARCHAR(500) NOT NULL
	,[State] NVARCHAR(500) NOT NULL
	,[Country] NVARCHAR(500) NOT NULL
	,[CreatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Created_At_Locations DEFAULT GETDATE()
)
