CREATE TABLE [dbo].[Purses]
(
	[Id] INT NOT NULL CONSTRAINT PK_Purse_Id PRIMARY KEY IDENTITY(1,1)
	,[Balance] MONEY NOT NULL CONSTRAINT DF_Balance_Purses DEFAULT (0.00)
	,[StayPlayBalance] MONEY NOT NULL CONSTRAINT DF_Stay_Play_Balance_Purses DEFAULT (0.00)
	,[PaidBonus] MONEY NOT NULL CONSTRAINT DF_Paid_Bonus_Purses DEFAULT (0.00)
	,[Currency] VARCHAR(3) NOT NULL
	,[CreatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Created_At_Purses DEFAULT GETDATE()
)
