CREATE TABLE [dbo].[Sports]
(
	[Id] INT NOT NULL CONSTRAINT PK_Sport_Id PRIMARY KEY IDENTITY(1,1)
	,[Name] NVARCHAR(255) NOT NULL
	,[Description] NVARCHAR(800) NULL
	,[CreatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Created_At_Sports DEFAULT GETDATE()
)
