CREATE TABLE [dbo].[UserGroups]
(
	[Id] INT NOT NULL CONSTRAINT PK_User_Groups PRIMARY KEY IDENTITY(1,1)
	,[Name] NVARCHAR(50) NOT NULL
	,[CreatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Created_At_UserGroups DEFAULT GETDATE()
)
