arrayWithSports = ['kayaking','bobsleigh','canoeing','cross-country skiing','rafting','skeleton','skibobbing','surfing','olympic swimming',
'bodyboarding','diving','freediving','paddleboarding','rowing','scuba diving','synchronized swimming','aerobics','aikido',
'archery','artistic gymnastics','baton twirling','bodybuilding','boxing','cross-country equestrianism','cross-country running',
'cycling','discus throw','equestrianism','fencing','figure skating','horse racing','judo','karate','kendo','kickboxing',
'kung fu','long jump','marathon','mixed martial arts','Muay Thai','pole vault','powerlifting','racewalking','rhythmic gymnastics',
'sprint','sumo','sword-fighting','trail running','trampolining','tumbling','ultimate','walking','weightlifting','wrestling',
'baseball','basketball','tennis','badminton','bowling','cricket','curling','dodgeball','football','golf','handball','hockey',
'horseball','hurling','ice hockey','kickball','lacrosse','paddle','polo','racquetball','rinkball','rounders','rugby','soccer',
'softball','squash','table tennis','unicycling basketball','unicycling handball','unicycling hockey','volleyball','water polo',
'BASE jumping','abseiling','bouldering','gliding','kiteboarding','kitesurfing','parachuting','paragliding','parasailing','skateboarding',
'skydiving','skysurfing','snowboarding','wakeboarding','windsurfing','climbing','cross-country cycling','hiking','mountaineering',
'drifting','formula racing','kart racing','rallycross','Go','bridge','checkers','chess','mahjong','airsoft','aquathlon','ballooning',
'barrel racing','biathlon','capoeira','cheerleading','CrossFit','dancing','darts','decathlon','foosball','gymkhana','heptathlon',
'jogging','laser tag','paintball','parkour','petanque','pool','triathlon']