CREATE TABLE [dbo].[DimMatch]
(
	[Id] INT NOT NULL CONSTRAINT PK_Matche_Id PRIMARY KEY IDENTITY(1,1)
	,[HomeTeam] NVARCHAR(1500) NOT NULL
	,[AwayTeam] NVARCHAR(1500) NOT NULL
	,[NameMatch] NVARCHAR(3100) NOT NULL
	,[IsStarted] BIT NOT NULL CONSTRAINT DF_Is_Started_DimMatch DEFAULT 0
	,[IsEnded] BIT NOT NULL CONSTRAINT DF_Is_Ended_DimMatch DEFAULT 0
	,[ScoreHomeTeam] INT NOT NULL CONSTRAINT DF_ScoreHomeTeam_DimMatch DEFAULT 0
	,[ScoreAwayTeam] INT NOT NULL CONSTRAINT DF_ScoreAwayTeam_DimMatch DEFAULT 0
	,[Date] DATETIME2 NOT NULL
)
